[package]
name = "fe2o3"
version = "0.1.0"
authors = ["dibyanshu <dibyanshu@gamezop.co>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"

[features]
big-primes = []
